# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qHqnR55wW6CwpntmshTmnv8SCNW6xm_h
"""

import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle

app = Flask(__name__)
model = pickle.load(open('model.pkl', 'rb'))

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict',methods=['POST'])
def predict():
    '''
    For rendering results on HTML GUI
    '''
    int_features = [int(x) for x in request.form.values()]
    final_features = [np.array(int_features)]
    prediction = model.predict(final_features)

    if prediction == 0:
      return render_template('index.html', prediction_text='Candidate not get Shortlisted!!')
    else:
       return render_template('index.html', prediction_text='Candidate get Shortlisted!!')
 
if __name__ == "__main__":
    app.run(debug=True)
