# -*- coding: utf-8 -*-
"""Predicting the Employee get hired or not.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sjjwCCNe083EJmyAUTALdy4BmCMeWG8x

**The objective this project is to predict whether the employee get hired or not based on the interview score and tests**
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
import pickle

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_excel('/content/drive/My Drive/DS Project/DeployementModelHeroku-CandidateHiring/CandidateDetails.xlsx')
data.head()
data.shape

X= data.iloc[ :,:4]
def convert_int(word):
  dict = {'Y':1,'N':0}
  return dict[word]

Y = data.iloc[:,-1].map(lambda X :convert_int(X))
Y

Model = LogisticRegression()
Model.fit(X,Y)
print(Model.predict([[3,4,3,5]]))

pickle.dump(Model,open('model.pkl', 'wb'))